# Generated by Django 4.0.4 on 2022-05-07 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('years_old', models.IntegerField(default=0)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='Phone number', max_length=128, region=None)),
                ('email', models.EmailField(default='Mail address', max_length=254)),
                ('photo', models.ImageField(upload_to='personnel_photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
