# Generated by Django 4.0.4 on 2022-05-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PasportCode',
            new_name='pasportCode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PasportDate',
            new_name='pasportDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PasportNum',
            new_name='pasportNum',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PasportOtd',
            new_name='pasportOtd',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Region',
            new_name='region',
        ),
    ]
